{
    "name": "Sale Rental",
    "version": "18.0.1.0.0",
    "category": "Sales",
    "license": "AGPL-3",
    "summary": "Manage Rental of Products",
    "author": "Akretion, Sodexis, Le Filament, Odoo Community Association (OCA)",
    "maintainers": ["alexis-via"],
    "website": "https://github.com/OCA/vertical-rental",
    "depends": ["sale_start_end_dates", "sale_stock", "sale_management"],
    "data": [
        "security/ir.model.access.csv",
        "security/sale_rental_security.xml",
        "data/rental_data.xml",
        "views/stock_warehouse.xml",
        "views/sale_rental.xml",
        "wizard/create_rental_product_view.xml",
        "views/product.xml",
        "views/sale_order.xml",
    ],
    "installable": True,
}
